/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.jackhammer2k.snappy.cli

import kotlin.test.Test

class SnappyCliTest {
    @Test
    fun appHasAGreeting() {
        // TODO
    }
}
